<Project>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk"/>

  <ItemGroup>
    <InternalsVisibleTo Include="Pacpar.Alpm.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZLinq" Version="1.5.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>

  <PropertyGroup>
    <BuildDependsOn>
    GenerateBindings;$(BuildDependsOn)
    </BuildDependsOn>
  </PropertyGroup>

  <Target Name="GenerateBindings">
    <Exec Command="cargo build -p libalpm-sys-cs" ConsoleToMsBuild="true"/>
  </Target>

</Project>
